# it is suggested that these be encrypted with ansible-vault:
# ansible-vault edit group_vars/windows.yml

# http://docs.ansible.com/ansible/intro_windows.html#windows-how-does-it-work

ansible_user: IEUser
ansible_password: Passw0rd
ansible_port: 5986
ansible_connection: winrm

# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore